Modified KEY name
I've just modified the key name because in docusaurus in alpha 2.0.0.67-alpha had still links as a KEY of the themeConfig.navabar.links but I got console shown

```
ValidationError: themeConfig.navbar.links has been renamed as themeConfig.navbar.items
```